### ISSUE TITLE
Add compartment quotas and usage against quotas

### ISSUE THREAD

**Issue by madmax33su** [turbot/steampipe-mod-oci-thrifty#31]
**Is your feature request related to a problem? Please describe.**
OCI allows to set compartment quotas for various resources.  Right now it is not easy to get a holistic picture of usage of resources against the quota limits.

**Describe the solution you'd like**
a module to report compartment quotas and usages

**Describe alternatives you've considered**
Manually checking quotas and usage in console

**Additional context**
Compartment quotas are used by organizations to control departments usage. Quotas helps to make sure individual departments (compartments) do not go over in budget.

**Comment by rajlearner17** [comment]
@kbsantosh1 Appreciate using Steampipe!! 👍 

That is an excellent suggestion; we see new go SDK support now available [here](https://github.com/oracle/oci-go-sdk/tree/17bbd776e290d540c7a2ee08b66d27192e2f5ddb/limits)

We have added a new issue in the [OCI Plugin](https://github.com/turbot/steampipe-plugin-oci/issues/403) to work on the feasibility

Meanwhile, let us know how Steampipe is helping in your use case; this will help us.
We are looking forward to more collaboration on this.
