### ISSUE TITLE
Report show Block Volumes which are in state TERMINATED

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-mod-oci-thrifty#7]
**Describe the bug**
Oracle Cloud Thrifty report shows recommendations for block volumes:  Block volumes should have auto-tune volume peformance enabled .. - but this BVs are already in state TERMINATED.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0steampipe version 0.7.1

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------+---------+---------------------------+
| Name                                       | Version | Connections               |
+--------------------------------------------+---------+---------------------------+
| hub.steampipe.io/plugins/turbot/oci@latest | 0.2.0   | oci_tenant_abcd        |
+--------------------------------------------+---------+---------------------------+

**To reproduce**
Terminate a Block Volume in OCI and re-run the report.

**Expected behavior**
TERMINATED components have to be removed from the report.

**Additional context**
Example - a comparison screenshot with the deleted BV is attached.

| + Block volumes should have auto-tune volume peformance enabled ...............................................................................................................  88 /  89 [===       ]
| | |
| | ALARM: ![bv_terminated](https://user-images.githubusercontent.com/56437524/131322898-8152d341-62b9-46ad-a883-f223cf6f3dce.png)auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB
| | ALARM: oidlab-oid200-volume auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB
| | ALARM: oidlab-oid204-volume auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB
| | ALARM: oidlab-oid205-volume auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB
| | ALARM: oidlab-oid201-volume auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB
| | ALARM: oidlab-oid203-volume auto-tune volume performance disabled. ............................................................................................................. eu-zurich-1 OID-LAB

**Comment by rajlearner17** [comment]
@martinberger-ch thanks for raising this, we are aware of this and working on the next release with change. Appreciate bringing this out. At the same time looking if we can filter out the same from the plugin table side.
